// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHB1Ksa5FSbvUrB-XgUB8KuOUpXDelauk',
    appId: '1:114922813238:web:dd87921baf5eac6303a597',
    messagingSenderId: '114922813238',
    projectId: 'agentic-coding-project',
    authDomain: 'agentic-coding-project.firebaseapp.com',
    storageBucket: 'agentic-coding-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHB1Ksa5FSbvUrB-XgUB8KuOUpXDelauk',
    appId: '1:114922813238:android:b0ec76a19958588d03a597',
    messagingSenderId: '114922813238',
    projectId: 'agentic-coding-project',
    storageBucket: 'agentic-coding-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHB1Ksa5FSbvUrB-XgUB8KuOUpXDelauk',
    appId: '1:114922813238:ios:7791fa5cf6a818bb03a597',
    messagingSenderId: '114922813238',
    projectId: 'agentic-coding-project',
    storageBucket: 'agentic-coding-project.firebasestorage.app',
    iosBundleId: 'com.parfolio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHB1Ksa5FSbvUrB-XgUB8KuOUpXDelauk',
    appId: '1:114922813238:ios:7791fa5cf6a818bb03a597',
    messagingSenderId: '114922813238',
    projectId: 'agentic-coding-project',
    storageBucket: 'agentic-coding-project.firebasestorage.app',
    iosBundleId: 'com.parfolio.app',
  );
}
